lexik_jwt_authentication:
    # secret_key: '%env(JWT_SECRET_KEY)%'
    # Cf servives.yaml
    secret_key: '%jwt_secret_key%'
    # public_key: '%env(JWT_PUBLIC_KEY)%'
    # Cf servives.yaml
    public_key: '%jwt_public_key%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600